# Generated by Django 3.2.5 on 2021-07-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='created_date',
        ),
    ]
