# Generated by Django 3.2.5 on 2021-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
